steps:
  - name: "node"
    entrypoint: "npm"
    args: ["--prefix", "backend", "build"]
    dir: "backend"
  - name: "node"
    entrypoint: "npm"
    args: ["--prefix", "backend", "start"]
    dir: "backend"
